module.exports={
    "user":require("./user"),
    "role": require("./role"),

    "client":require("./gestao-oportunidades/client"),        
    "pedidos_clientes": require("./gestao-oportunidades/pedidos_clientes"),
    "eventos": require("./gestao-oportunidades/eventos"),
    "propostas": require("./gestao-oportunidades/propostas"),
    "analises_preliminares": require("./gestao-oportunidades/analises_preliminares"),
    "designacao_objeto": require("./technical-form/designacao_objecto")
    /*"categorias": require("./technical-form/categorias"),
    "sub_categorias": require("./technical-form/sub_categorias"),
    "pessoa": require("./technical-form/pessoa"),
    "designacao_objecto": require("./technical-form/designacao_objecto"),
    "condicoes_ambientais": require("./technical-form/condicoes_ambientais"),
    "condicoes_iluminacao": require("./technical-form/condicoes_iluminacao"),
    "condicoes_poluicao": require("./technical-form/condicoes_poluicao"),
    "conjuntos": require("./technical-form/conjuntos"),
    "contacto": require("./technical-form/contacto"),
    "descricao_biologica": require("./technical-form/descricao_biologica"),
    "descricao_fisica": require("./technical-form/descricao_fisica"),
    "descricao_material": require("./technical-form/descricao_material"),
    "descricao_patrimonial": require("./technical-form/descricao_patrimonial"),
    "descricao_tecnica": require("./technical-form/descricao_tecnica"),
    "detalhes_estado_conservacao": require("./technical-form/detalhes_estado_conservacao"),
    "detalhes_exames": require("./technical-form/detalhes_exames"),
    "documentacao": require("./technical-form/documentacao"),
    "fotos": require("./technical-form/fotos"),
    "intervencao_proposta": require("./technical-form/intervencao_proposta"),
    "intervencao_realizada": require("./technical-form/intervencao_realizada"),
    "intervencoes_anteriores": require("./technical-form/intervencoes_anteriores"),
    "membro_equipa": require("./technical-form/membro_equipa"),
    "objectivos_gerais": require("./technical-form/objectivos_gerais"),
    "objectivos_gerais_usados": require("./technical-form/objectivos_gerais_usados"),
    "objecto_equipa": require("./technical-form/objecto_equipa"),
    "proposta_metodologia_intervencao": require("./technical-form/proposta_metodologia_intervencao"),
    "tabela_exames_analises": require("./technical-form/tabela_exames_analises"),
    "vontade_intervencao_proprietario": require("./technical-form/vontade_intervencao_proprietario")*/
}
